# Generated by GitHub Copilot on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
