
services:
  web:
    build: backend/
    ports:
      - "8000:8000"
    networks:
      - AirbNet
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres.wtbmqtmmdobfvvecinif
      DATABASE_PASSWORD: Mayache+123455
      DATABASE_HOST: aws-1-eu-north-1.pooler.supabase.com
      DATABASE_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: amine
      DJANGO_SUPERUSER_EMAIL: amine@a.com
      DJANGO_SUPERUSER_PASSWORD: amineamine
      LOAD_INITIAL_FIXTURE: "1"
      
    restart: unless-stopped

  app:
    build: frontend/
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1.5G
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DJANGO_API_URL=http://web:8000
      - NEXT_PUBLIC_DJANGO_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres.wtbmqtmmdobfvvecinif:Mayache+123455@aws-1-eu-north-1.pooler.supabase.com:5432/postgres
      - NODE_OPTIONS=--max-old-space-size=4096 --openssl-legacy-provider
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=2000
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    networks:
      - AirbNet
    restart: unless-stopped


networks:
  AirbNet:
    driver: bridge