# Generated by Django 4.2.21 on 2025-11-20 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_back_document',
            field=models.ImageField(blank=True, help_text='Back side of identity document', null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_document',
            field=models.ImageField(blank=True, help_text='Front side of identity document', null=True, upload_to='identity_documents/'),
        ),
    ]
