# Generated by Django 5.2.5 on 2025-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seating_capacity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(default='manual', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_condition',
            field=models.CharField(default='good', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='agree_on_terms',
            field=models.BooleanField(default=False),
        ),
    ]
