# Generated by Django 4.2.21 on 2025-09-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_available_features_listing_fuel_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='license_info',
            new_name='license_number',
        ),
    ]
