# Generated by Django 4.2.21 on 2025-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_contact_and_login_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_username',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='login_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='login_password',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='login_username',
        ),
        migrations.AlterField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
