# Generated by Django 4.2.21 on 2025-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_back_document_url',
            field=models.URLField(blank=True, help_text='Supabase URL for back identity document', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_document_url',
            field=models.URLField(blank=True, help_text='Supabase URL for front identity document', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_back_document',
            field=models.ImageField(blank=True, help_text='Back side of identity document (local storage)', null=True, upload_to='identity_documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_front_document',
            field=models.ImageField(blank=True, help_text='Front side of identity document (local storage)', null=True, upload_to='identity_documents/'),
        ),
    ]
