# Generated by Django 5.2.5 on 2025-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='id_back_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
