# Generated by Django 4.2.21 on 2025-09-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_license_info_user_license_number'),
        ('core', '0004_remove_partner_contact_email_and_more'),
    ]

    operations = [
    ]
