# Generated by Django 4.2.21 on 2025-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250904_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
