# Generated by Django 4.2.21 on 2025-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_name_user_id_back_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_back_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_front_document',
        ),
        migrations.AddField(
            model_name='listing',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_back_document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
