# Generated by Django 4.2.21 on 2025-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_id_back_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, db_column='profile_picture_url', null=True),
        ),
    ]
