# Generated by Django 4.2.21 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner company logo', null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Public URL for logo hosted on Supabase', max_length=500, null=True),
        ),
    ]
