# Generated by Django 4.2.21 on 2025-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, help_text='Partner company description', null=True),
        ),
    ]
