# Generated by Django 4.2.21 on 2025-09-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_id_expiry_date_remove_user_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
