# Generated by Django 4.2.21 on 2025-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available_features',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='pictures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
