# Generated by Django 4.2.21 on 2025-09-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_partner_verification_status'),
        ('core', '0011_remove_listing_available_features_and_more'),
    ]

    operations = [
    ]
