# Generated by Django 4.2.21 on 2025-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_profile_picture_base64'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='core_bookin_pickup__f28a9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='core_listin_price_p_10eadd_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded profile picture (data:image/jpeg;base64,...)', null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'status'], name='core_bookin_listing_8de718_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pickup_date', 'return_date', 'status'], name='core_bookin_pickup__d84726_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pickup_date'], name='core_bookin_status_454c61_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='core_bookin_created_f24220_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='core_favori_user_id_70210b_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['listing'], name='core_favori_listing_fa880b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_available', 'is_verified'], name='core_listin_is_avai_2dcd17_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_day', 'is_available'], name='core_listin_price_p_29f65d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['rating', 'review_count'], name='core_listin_rating_96bbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['partner', 'is_available'], name='core_listin_partner_8214ee_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='core_listin_created_dcbb19_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['transmission'], name='core_listin_transmi_2280a0_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['fuel_type'], name='core_listin_fuel_ty_8e61ce_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['vehicle_style'], name='core_listin_vehicle_365d73_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seating_capacity'], name='core_listin_seating_428cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['listing', 'is_published', 'created_at'], name='core_review_listing_4bdd42_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='core_review_user_id_9e69dc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='core_review_rating_41e437_idx'),
        ),
    ]
