# Generated by Django 4.2.21 on 2025-09-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250914_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
