# Generated by Django 4.2.21 on 2026-01-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_back_document',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id_back_document_url',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id_front_document',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id_front_document_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_back_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_back_document_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_front_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_front_document_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_back_document_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_front_document_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_base64',
        ),
    ]
