# Generated by Django 4.2.21 on 2025-10-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fix_booking_listing_cascade'),
    ]

    operations = [
    ]
