# Generated by Django 4.2.21 on 2025-10-13 15:07

from django.db import migrations

def fix_booking_listing_constraint(apps, schema_editor):
    # Run custom SQL to fix the foreign key constraint
    # This part will execute directly on the database
    schema_editor.execute("""
    ALTER TABLE core_booking 
    DROP CONSTRAINT IF EXISTS core_booking_listing_id_582d4cc6_fk_core_listing_id;

    ALTER TABLE core_booking 
    ADD CONSTRAINT core_booking_listing_id_582d4cc6_fk_core_listing_id 
    FOREIGN KEY (listing_id) 
    REFERENCES core_listing(id) 
    ON DELETE CASCADE;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_partner_verification_status'),
    ]

    operations = [
        migrations.RunPython(fix_booking_listing_constraint),
    ]
