# Generated by Django 4.2.21 on 2026-02-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ensure_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
    ]
