# Generated by Django 4.2.21 on 2025-10-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_booking_listing_cascade'),
        ('core', '0016_fix_booking_listing_cascade'),
    ]

    operations = [
    ]
