# Generated by Django 4.2.21 on 2026-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_booking_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_back_document_url',
            field=models.URLField(blank=True, help_text='Public URL for back license hosted on Supabase', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_front_document_url',
            field=models.URLField(blank=True, help_text='Public URL for front license hosted on Supabase', max_length=500, null=True),
        ),
    ]
