# Generated by Django 4.2.21 on 2026-02-06 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_address_city_state_to_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate'), ('harassment', 'Harassment'), ('false_info', 'False Information'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_cust_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_partner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_listing_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_status_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='favorite_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_avail_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_partner_avail_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_verified_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_listing_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_listing_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if user had a completed booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_back_document',
            field=models.ImageField(blank=True, help_text='Back side of driver license', null=True, upload_to='user_documents/license_documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_front_document',
            field=models.ImageField(blank=True, help_text='Front side of driver license', null=True, upload_to='user_documents/license_documents/'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.review'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['review', 'user'], name='core_review_review__f8ceb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review'], name='core_review_review__bcf44c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'user')},
        ),
    ]
