# Generated by Django 4.2.21 on 2026-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_review_reply_and_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡')], max_length=10),
        ),
    ]
