# Generated by Django 4.2.21 on 2026-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_removed_favorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='removedfavorite',
            new_name='core_remove_user_id_b86ea5_idx',
            old_name='removedfav_user_removed_idx',
        ),
        migrations.RenameIndex(
            model_name='removedfavorite',
            new_name='core_remove_listing_23269f_idx',
            old_name='removedfav_listing_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('admin', 'Admin'), ('ceo', 'CEO')], default='customer', max_length=20),
        ),
    ]
