# Generated by Django 4.2 on 2026-04-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_removedfav_user_removed_idx_core_remove_user_id_b86ea5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('profile_update', 'Profile Update'), ('user_upload', 'User Document Upload'), ('booking_create', 'Booking Create')], max_length=30)),
                ('is_valid', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('detected_country', models.CharField(blank=True, default='UNKNOWN', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('front_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('back_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_verifications', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='licenseverificationrecord',
            index=models.Index(fields=['user', 'created_at'], name='core_licens_user_id_a4d951_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseverificationrecord',
            index=models.Index(fields=['context', 'created_at'], name='core_licens_context_964c07_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseverificationrecord',
            index=models.Index(fields=['is_valid', 'created_at'], name='core_licens_is_vali_194fff_idx'),
        ),
    ]
