# Generated by Django 4.2 on 2026-04-13 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_user_follows_and_trip_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs if provided')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='listingcomment',
            new_name='core_listin_listing_7a5e9b_idx',
            old_name='core_listco_listing_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='listingcomment',
            new_name='core_listin_parent__4ee215_idx',
            old_name='core_listco_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='listingcomment',
            new_name='core_listin_user_id_eede9a_idx',
            old_name='core_listco_user_idx',
        ),
        migrations.RenameIndex(
            model_name='listingreaction',
            new_name='core_listin_listing_d4cc8e_idx',
            old_name='core_listreact_listing_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerfollow',
            new_name='core_partne_user_id_f37238_idx',
            old_name='core_partfollow_user_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerfollow',
            new_name='core_partne_partner_4a922f_idx',
            old_name='core_partfollow_partner_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerpost',
            new_name='core_partne_partner_dec1b1_idx',
            old_name='core_partpost_partner_active_idx',
        ),
        migrations.RenameIndex(
            model_name='trippost',
            new_name='core_trippo_user_id_613e28_idx',
            old_name='core_trippost_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='trippost',
            new_name='core_trippo_is_acti_ba1a69_idx',
            old_name='core_trippost_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trippostcomment',
            new_name='core_trippo_trip_po_665cdf_idx',
            old_name='core_tripcmt_trippost_active_idx',
        ),
        migrations.RenameIndex(
            model_name='trippostcomment',
            new_name='core_trippo_parent__d3ee76_idx',
            old_name='core_tripcmt_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='trippostreaction',
            new_name='core_trippo_trip_po_e477e0_idx',
            old_name='core_tripreact_trippost_idx',
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='core_userfo_followe_9a7a3f_idx',
            old_name='core_userfollow_follower_idx',
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='core_userfo_followi_9cfb07_idx',
            old_name='core_userfollow_following_idx',
        ),
        migrations.AlterField(
            model_name='trippost',
            name='booking',
            field=models.OneToOneField(help_text='Must be a completed booking owned by this user.', on_delete=django.db.models.deletion.CASCADE, related_name='trip_post', to='core.booking'),
        ),
        migrations.AlterField(
            model_name='trippost',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of Supabase image URLs'),
        ),
        migrations.AddField(
            model_name='communitypostreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.communitypost'),
        ),
        migrations.AddField(
            model_name='communitypostreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.communitypostcomment'),
        ),
        migrations.AddField(
            model_name='communitypostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.communitypost'),
        ),
        migrations.AddField(
            model_name='communitypostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_mentions', to='core.listing'),
        ),
        migrations.AddIndex(
            model_name='communitypostreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='core_commun_post_id_41b747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostreaction',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['post', 'is_active', 'created_at'], name='core_commun_post_id_ce24ab_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['parent'], name='core_commun_parent__bff71e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_active', '-created_at'], name='core_commun_is_acti_3e960e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author', '-created_at'], name='core_commun_author__9522d6_idx'),
        ),
    ]
