# Generated by Django 4.2.21 on 2026-04-13 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_communitypost_communitypostcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='luggage_capacity',
            field=models.CharField(blank=True, help_text="e.g., '2 Large Bags'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='range_km',
            field=models.CharField(blank=True, help_text="e.g., 'Unlimited', '450 km'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='elite_status',
            field=models.IntegerField(default=1, help_text='1 to 5 level for Kinetic Concierge', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='partner',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Years in the business, e.g. 12'),
        ),
        migrations.AddField(
            model_name='partner',
            name='response_time',
            field=models.CharField(blank=True, default='< 1 hour', help_text="e.g., '< 15 mins'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='communitypostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='core.communitypost'),
        ),
        migrations.AlterField(
            model_name='communitypostreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='core.communitypost'),
        ),
        migrations.AlterField(
            model_name='listingcomment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='core.listing'),
        ),
        migrations.AlterField(
            model_name='listingreaction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='core.listing'),
        ),
        migrations.AlterField(
            model_name='reviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='core.review'),
        ),
        migrations.AlterField(
            model_name='trippostcomment',
            name='trip_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='core.trippost'),
        ),
        migrations.AlterField(
            model_name='trippostreaction',
            name='trip_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='core.trippost'),
        ),
    ]
