# Generated by Django 4.2 on 2026-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_listing_luggage_capacity_listing_range_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='username',
            field=models.CharField(blank=True, help_text='Unique agency handle', max_length=50, null=True, unique=True),
        ),
    ]
