# Generated by Django 4.2.21 on 2026-04-15 23:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_partner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, help_text='Public short ID for inter-agency sharing', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CarShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Agreed B2B rental price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='core.listing')),
                ('owner', models.ForeignKey(help_text='Agency owning the car', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_share_requests', to='core.partner')),
                ('requester', models.ForeignKey(help_text='Agency requesting the car', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_share_requests', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
