# Generated by Django 4.2.21 on 2026-04-16 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_listing_public_id_carsharerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('mileage', models.IntegerField()),
                ('fuel_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('images', models.JSONField(blank=True, default=list)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_share_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.carsharerequest')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_recorded', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_share_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.carsharerequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_messages', to='core.partner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
