# Generated by Django 4.2.21 on 2025-11-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('agree_on_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='partner_docs/')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for public profile', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Company description for public profile', max_length=1000, null=True)),
                ('logo', models.URLField(blank=True, help_text='Company logo URL', null=True)),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('business_type', models.CharField(blank=True, help_text='Type of business (individual, company, fleet, dealership)', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text='Business address', max_length=500, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Zip/Postal code', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_partner',
                'indexes': [models.Index(fields=['verification_status'], name='core_partne_verific_d03d23_idx'), models.Index(fields=['slug'], name='core_partne_slug_4e9d41_idx')],
            },
        ),
    ]
