# Generated by Django 4.2.21 on 2025-11-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=25)),
                ('seating_capacity', models.IntegerField()),
                ('vehicle_condition', models.CharField(max_length=50)),
                ('vehicle_description', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('features', models.JSONField(default=list)),
                ('pictures', models.JSONField(blank=True, default=list)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='partners.partner')),
            ],
            options={
                'db_table': 'core_listing',
            },
        ),
    ]
