# Generated by Django 4.2.21 on 2025-11-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='core_user_email_38052c_idx',
            old_name='users_user_email_6f2530_idx',
        ),
    ]
